config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :issues, only: %i[create]
    end
  end

  namespace :admin do
    resources :clients, except: [:destroy]
    resources :users, except: [:destroy]
    resources :writings
    resources :photos
    resources :presses
    resources :clays
    resources :glazes
    resources :glaze_combinations

    root to: 'clients#index'

    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :api do
    namespace :v1 do
    end
  end

  namespace :user do
    resources :events
  end

  resource :about, only: [:show]
  resources :writings, only: [:index]
  resources :presses, only: [:index]
  resource :photography, only: [:show]
  resource :lessons, only: [:show]
  resource :studio_share, only: [:show]
  resource :studio, only: [:show]
  resource :engineering_resume, only: [:show]
  resource :ceramics_resume, only: [:show]
  resource :kiln_share, only: [:show]
  resource :store, only: [:show]
  resource :contact, only: [:show, :update]
  resource :purpose, only: [:show]
  root to: 'abouts#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    primary_abstract_class
end

app/models/clay.rb
class Clay < ApplicationRecord
  validates :identifier, :name, :shrinkage, :absorption, :description, :url, presence: true
end

app/models/client.rb
class Client < ApplicationRecord
  encrypts :api_key, deterministic: true
  validates :name, :api_key, presence: true, uniqueness: true
end

app/models/glaze.rb
class Glaze < ApplicationRecord
    enum :minimum_cone, { "04": "04", "5": "5", "6": "6" }, prefix: true, scopes: false
    enum :maximum_cone, { "04": "04", "5": "5", "6": "6" }, prefix: true, scopes: false
    enum :primary_color, { "red": "red", "orange": "orange", "yellow": "yellow", "green": "green", "blue": "blue", "purple": "purple", "pink": "pink", "brown": "brown", "black": "black", "white": "white", "gray": "gray", "gold": "gold", "silver": "silver"}, prefix: true, scopes: false
  
    has_one_attached :test_tile_photo
  
    validates :identifier, :name, :description, :minimum_cone, :maximum_cone, presence: true
    validates :food_safe, inclusion: [true, false]

    def cone_range
      if minimum_cone == maximum_cone
        minimum_cone
      else
        "#{minimum_cone}–#{maximum_cone}"
      end
    end

    def canonical_identifier
      identifier
    end
  end

app/models/glaze_combination.rb
class GlazeCombination < ApplicationRecord
    enum :primary_color, { "red": "red", "orange": "orange", "yellow": "yellow", "green": "green", "blue": "blue", "purple": "purple", "pink": "pink", "brown": "brown", "black": "black", "white": "white", "gray": "gray", "gold": "gold", "silver": "silver"}, prefix: true, scopes: false

    has_one_attached :test_tile_photo
    
    belongs_to :first_glaze, class_name: "Glaze"
    belongs_to :second_glaze, class_name: "Glaze"
  
    validates :name, :description, :first_glaze, :second_glaze, presence: true

    def cone_range
      minimum_cone = [first_glaze.minimum_cone, second_glaze.minimum_cone].sort_by { |cone| Glaze.minimum_cones.keys.index(cone) }.last
      maximum_cone = [second_glaze.maximum_cone, second_glaze.maximum_cone].sort_by { |cone| Glaze.maximum_cones.keys.index(cone) }.first

      if minimum_cone == maximum_cone
        minimum_cone
      else
        "#{minimum_cone}–#{maximum_cone}"
      end
    end

    def canonical_identifier
      "#{first_glaze.identifier}×#{second_glaze.identifier}"
    end

    def food_safe
      first_glaze.food_safe && second_glaze.food_safe
    end
  end

app/models/photo.rb
class Photo < ApplicationRecord
    enum :category, { "portrait": "portrait", "landscape": "landscape", "other": "other" }, prefix: true, scopes: false
    has_one_attached :photo
  
    validates :category, presence: true
  end

app/models/press.rb
class Press < ApplicationRecord
  has_one_attached :photo

  validates :title, :description, :url, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :validatable, :confirmable, :lockable # , :registerable
end

app/models/writing.rb
class Writing < ApplicationRecord
  validates :title, :description, :url, presence: true
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def show
    render
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  def after_sign_in_path_for(resource)
    admin_path
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def show
    render
  end

  def update
    params.permit(:name, :email, :message)

    ActionMailer::Base.mail(
      from: Rails.configuration.email[:from_address],
      to: "wil@wilhall.com",
      reply_to: params[:email],
      subject: "wilhall.com: Message from #{params[:name]} (#{params[:email]})",
      body: params[:message]
    ).deliver

    redirect_to contact_path, notice: "Your message has been received! I'll be in touch soon."
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  layout "error"

  def show
    @app_name = Rails.application.class.module_parent_name
    @request_id = request.request_id
    @exception = request.env["action_dispatch.exception"]
    @status_code = @exception.try(:status_code) ||
      ActionDispatch::ExceptionWrapper.new(
        request.env, @exception
      ).status_code

    render view_for_code(@status_code), status: @status_code
  end

  private

  def view_for_code(code)
    supported_error_codes.fetch(code, "404")
  end

  def supported_error_codes
    {
      404 => "404",
      500 => "500"
    }
  end
end

app/controllers/kiln_shares_controller.rb
class KilnSharesController < ApplicationController
  def show
    render
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def show
    render
  end
end

app/controllers/presses_controller.rb
class PressesController < ApplicationController
  def index
    @presses = Press.all
    render
  end
end

app/controllers/purposes_controller.rb
class PurposesController < ApplicationController
  def show
    render
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def show
    render
  end
end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  def show
    params.permit(:base_glaze, :primary_color)

    @clays = Clay.all
    @base_glaze_options = Glaze.all.pluck(Arel.sql("identifier || ' ' || name"))
    @primary_color_options = Glaze.primary_colors.keys.map(&:titleize)

    @selected_base_glaze = params[:base_glaze]
    @selected_primary_color = params[:primary_color]

    @glazes = Glaze.all
    @glaze_combinations = GlazeCombination.all

    if @selected_base_glaze.present?
      identifier, name = @selected_base_glaze.split(' ', 2)
      @glazes = @glazes.where(identifier: identifier)
      @glaze_combinations = @glaze_combinations.joins(:first_glaze).where(first_glaze: {identifier: identifier})
    end

    if @selected_primary_color.present?
      @glazes = @glazes.where(primary_color: @selected_primary_color.downcase)
      @glaze_combinations = @glaze_combinations.where(primary_color: @selected_primary_color.downcase)
    end

    render
  end
end

app/controllers/writings_controller.rb
class WritingsController < ApplicationController
  def index
    @writings = Writing.all
    render
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include ActionView::Helpers::DurationHelper
end

app/views/kiln_shares/show.html.erb
<% content_for :title do %>
  Wil Hall - Kiln Share
<% end %>
<article class="py-8 md:py-16 antialiased">
  <div class="max-w-screen-xl px-4 mx-auto 2xl:px-0">
    <div class="lg:grid lg:grid-cols-2 lg:gap-8 xl:gap-16">
      <div class="shrink-0 h-min max-w-md lg:max-w-lg mx-auto rounded-md shadow-lg border-slate-300 border-2 overflow-hidden">
        <img class="w-full" src="/photos/kiln.png" alt=""/>
      </div>
      <div class="mt-6 sm:mt-8 lg:mt-0">
        <h1
          class="text-2xl font-semibold text-slate-900 sm:text-3xl"
        >
          Kiln Share
        </h1>
        <div class="mt-4 sm:items-center sm:gap-4 sm:flex">
          <p
            class="text-xl font-bold text-slate-900 sm:text-2xl"
          >
            $20&ndash;$85
          </p>
        </div>
        <div class="mt-6 sm:gap-4 sm:items-center sm:flex sm:mt-8">
          <a
          data-umami-event="Kiln Share - Schedule a dropoff"
          href="https://booking.wilhall.com/kiln-share-dropoff"
          target="_blank"
          class="flex items-center justify-center py-2.5 px-5 text-sm font-medium text-white focus:outline-none bg-secondary rounded-lg border border-slate-200 hover:opacity-80 hover:text-primary-700 focus:z-10 focus:ring-4 focus:ring-slate-100"
          role="button"
        >
          Schedule a dropoff
        </a>
        <a
        data-umami-event="Kiln Share - Schedule a pickup"
        href="https://booking.wilhall.com/schedule-a-pickup"
        target="_blank"
        class="flex items-center justify-center py-2.5 px-5 text-sm font-medium text-white focus:outline-none bg-secondary rounded-lg border border-slate-200 hover:opacity-80 hover:text-primary-700 focus:z-10 focus:ring-4 focus:ring-slate-100"
        role="button"
      >
        Schedule a pickup
      </a>
        </div>
        <hr class="my-6 md:my-8 border-slate-200"/>
        <div class="text-slate-700 prose">

          <%= render partial: "kiln_share_description" %>

          <p class="font-bold">
            Pricing:
          </p>
          <table class="border border-slate-200 py-2 px-5">
          <thead class="bg-blue-50">
            <tr>
              <th scope="col" class="text-left px-4 py-2">Space</th>
              <th scope="col" class="text-left px-4 py-2">Price</th>
            </tr>
          </thead>
          <tbody>
            <tr class="bg-white border-b">
              <th class="text-left font-bold px-4 py-2 font-medium">Bisque 1 shelf (17in x 17in)</th>
              <td class="px-4 py-2 font-medium">$20</td>
            </tr>
            <tr class="bg-white border-b">
              <th class="text-left font-bold px-4 py-2 font-medium">Glaze 1 shelf (17in x 17in)</th>
              <td class="px-4 py-2 font-medium">$25</td>
            </tr>
            <tr class="bg-white border-b">
              <th class="text-left font-bold px-4 py-2 font-medium">Bisque Full Kiln</th>
              <td class="px-4 py-2 font-medium">$70</td>
            </tr>
            <tr class="bg-white border-b">
              <th class="text-left font-bold px-4 py-2 font-medium">Glaze Full Kiln</th>
              <td class="px-4 py-2 font-medium">$85</td>
            </tr>
          </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</article>

app/views/lessons/show.html.erb
<% content_for :title do %>
  Wil Hall - Pottery Lessons
<% end %>
<% content_for :meta do %>
  <meta property="og:title" content="Wil Hall - Pottery Lessons"/>
  <meta property="og:description" content="A private wheel-throwing pottery lesson taught out of my home studio in Somerville, MA near Davis Square - no prior experience required, and all materials and tools are included."/>
  <meta property="og:image" content="https://wilhall.com/photos/lesson.png"/>
  <meta name="description" content="Private wheel-throwing pottery lessons taught out of my home studio in Somerville, MA near Davis Square - no prior experience required, and all materials and tools are included.">
<% end %>

<article class="py-8 md:py-16 antialiased">
  <div class="max-w-screen-xl px-4 mx-auto 2xl:px-0">
    <div class="lg:grid lg:grid-cols-2 lg:gap-8 xl:gap-16">
      <div class="shrink-0 h-min max-w-md lg:max-w-lg mx-auto overflow-hidden relative pb-10">
        <div class="swiper-container" data-controller="swiper">
          <div class="swiper-wrapper">
            <div class="swiper-slide rounded-md shadow-lg border-slate-300 border-2">
              <img class="w-full" src="/photos/lesson.png" alt=""/>
            </div>
            <div class="swiper-slide rounded-md shadow-lg border-slate-300 border-2">
              <img class="w-full" src="/photos/example_1.png" alt=""/>
            </div>
            <div class="swiper-slide rounded-md shadow-lg border-slate-300 border-2">
              <img class="w-full" src="/photos/example_2.png" alt=""/>
            </div>
            <div class="swiper-slide rounded-md shadow-lg border-slate-300 border-2">
              <img class="w-full" src="/photos/example_3.png" alt=""/>
            </div>
          </div>
          <div class="swiper-pagination"></div>
          <div class="swiper-button-next drop-shadow-xl"></div>
          <div class="swiper-button-prev drop-shadow-xl"></div>
        </div>
      </div>

      <div class="mt-6 sm:mt-8 lg:mt-0">
        <h1
          class="text-2xl font-semibold text-slate-900 sm:text-3xl"
        >
          Pottery Lessons
        </h1>
        <div class="mt-4 sm:items-center sm:gap-4 sm:flex">
          <p
            class="text-xl font-bold text-slate-900 sm:text-2xl"
          >
            $150<small>/month</small>
          </p>
        </div>

        <div class="mt-6 sm:gap-4 sm:items-center sm:flex sm:mt-8">
          <a
            data-umami-event="Start a Student Monthly Membership"
            href="https://buy.stripe.com/dR67sR8Gi8rYfEk00G"
            target="_blank"
            class="flex items-center justify-center py-2.5 px-5 text-sm font-medium text-white focus:outline-none bg-secondary rounded-lg border border-slate-200 hover:opacity-80 hover:text-primary-700 focus:z-10 focus:ring-4 focus:ring-slate-100"
            role="button"
          >
            Start a Student Monthly Membership
          </a>
        </div>

        <div class="mt-6 sm:gap-4 sm:items-center sm:flex sm:mt-8">
          <a
            href="<%= studio_path %>"
            class="flex items-center justify-center py-1 px-3 text-sm text-secondary font-medium focus:outline-none bg-white rounded-lg border-2 border-secondary hover:opacity-80 hover:text-primary-700 focus:z-10 focus:ring-4 focus:ring-slate-100"
            role="button"
          >
            Studio Information
          </a>
        </div>

        <hr class="my-6 md:my-8 border-slate-200"/>

        <div class="text-slate-700 prose">
          <%= render partial: "studios/memberships" %>
        </div>
      </div>
    </div>
  </div>
</article>

app/views/stores/show.html.erb
<% content_for :title do %>
  Wil Hall - Store
<% end %>

<% content_for :logo do %>
  <%= render 'shared/plume_and_pith_logo' %>
<% end %>

<article class="mx-auto grid grid-cols-1 lg:grid-cols-2 gap-3">
  <a href="<%= lessons_path %>" class="mx-auto flex flex-col items-center bg-white border border-slate-200 rounded-md shadow md:flex-row md:max-w-xl hover:border-secondary">
    <img class="object-cover w-full rounded-t-md h-96 md:h-auto md:w-48 md:rounded-none md:rounded-s-md" src="/photos/lesson.png" alt="">
    <div class="flex flex-col justify-between p-4 leading-normal">
      <h2 class="flex items-center gap-3 mb-2 text-2xl font-bold tracking-tight text-secondary">
        <span>Pottery Lessons</span>
        <i class="text-2xl fa-solid fa-chevron-right"></i></h2>
      <p class="mb-3 font-normal text-slate-700">Wheel-throwing pottery lessons taught from my home studio. Can be
        geared towards any skill level and accomodate up to two people at a time.</p>
    </div>
  </a>
  <a href="<%= studio_share_path %>" class="mx-auto flex flex-col items-center bg-white border border-slate-200 rounded-md shadow md:flex-row md:max-w-xl hover:border-secondary">
    <img class="object-cover w-full rounded-t-md h-96 md:h-auto md:w-48 md:rounded-none md:rounded-s-md" src="/photos/studio.png" alt="">
    <div class="flex flex-col justify-between p-4 leading-normal">
      <h2 class="flex items-center gap-3 mb-2 text-2xl font-bold tracking-tight text-secondary">
        <span>Studio Share</span>
        <i class="text-2xl fa-solid fa-chevron-right"></i></h2>
      <p class="mb-3 font-normal text-slate-700">Use my studio space to make your own work whether it be throwing or
        handbuilding. Clay, decorating supplies, and firing are available.</p>
    </div>
  </a>
  <a href="<%= kiln_share_path %>" class="mx-auto flex flex-col items-center bg-white border border-slate-200 rounded-md shadow md:flex-row md:max-w-xl hover:border-secondary">
    <img class="object-cover w-full rounded-t-md h-96 md:h-auto md:w-48 md:rounded-none md:rounded-s-md" src="/photos/kiln.png" alt="">
    <div class="flex flex-col justify-between p-4 leading-normal">
      <h2 class="flex items-center gap-3 mb-2 text-2xl font-bold tracking-tight text-secondary">
        <span>Kiln Share</span>
        <i class="text-2xl fa-solid fa-chevron-right"></i></h2>
      <p class="mb-3 font-normal text-slate-700">Drop off work to be bisque or glaze fired, only pay for the space you use.</p>
    </div>
  </a>
</article>

app/views/studios/show.html.erb
<% content_for :title do %>
  Wil Hall - Studio
<% end %>
<% content_for :logo do %>
  <%= render 'shared/plume_and_pith_logo' %>
<% end %>
<div class="flex flex-wrap font-medium text-slate-700 bg-white rounded-md shadow-lg border border-slate-200 py-2 px-5">
  <input name="tabs" tabindex="1" type="radio" id="#guide" class="absolute cursor-pointer w-0 opacity-0"/>
  <label for="#guide" class="cursor-pointer inline-flex items-center justify-center gap-2 p-4 font-bold border-b-2 border-transparent rounded-t-lg hover:text-slate-600 hover:border-slate-300 border-blue-600">
    <i class="block fa-solid fa-book text-slate-700 text-xl"></i>
    Guide
  </label>
  <div class="panel my-5">
    <div class="prose mx-auto">
      <%= render partial: "guide", locals: local_assigns %>
    </div>
  </div>
  <input name="tabs" tabindex="1" type="radio" id="#glazes" class="absolute cursor-pointer w-0 opacity-0"/>
  <label for="#glazes" class="cursor-pointer inline-flex items-center justify-center gap-2 p-4 font-bold border-b-2 border-transparent rounded-t-lg hover:text-slate-600 hover:border-slate-300 border-blue-600">
    <i class="block fa-solid fa-swatchbook text-slate-700 text-xl"></i>
    Glazes
  </label>
  <div class="panel my-5">
    <%= form_with(url: studio_path, method: :get, data: { controller: "filter" }, class: "flex gap-3 w-full items-end flex-wrap") do %>
      <div class="flex flex-col">
        <%= label_tag :base_glaze, "Base Glaze", class: "font-bold" %>
        <%= select_tag :base_glaze,
                            options_for_select(@base_glaze_options,
                                                selected: @selected_base_glaze),
                            prompt: "Any",
                            class: 'rounded-lg border-slate-300',
                            data: { action: "change->filter#submit" } %>
      </div>
      <div class="flex flex-col">
        <%= label_tag :primary_color, "Primary Color", class: "font-bold" %>
        <%= select_tag :primary_color,
                            options_for_select(@primary_color_options,
                                                selected: @selected_primary_color),
                            prompt: "Any",
                            class: 'rounded-lg border-slate-300',
                            data: { action: "change->filter#submit" } %>
      </div>
    <% end %>
    <% if (@glazes + @glaze_combinations).empty? %>
      <div class="text-center text-xl font-bold w-full my-5">No glazes found</div>
    <% else %>
      <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3 my-5">
        <% (@glazes + @glaze_combinations).each do |glaze| %>
          <div class="bg-white border border-slate-200 rounded-md">
            <img class="rounded-t-md" src="<%= url_for(glaze.test_tile_photo) %>" alt=""/>
            <div class="p-5">
              <h2 class="flex items-center gap-3 text-black text-2xl font-bold tracking-tight">
                <%= glaze.name %>
              </h2>
              <span class="text-secondary font-bold">
                <%= glaze.canonical_identifier %>
              </span>
              <div class="flex gap-3 items-center">
                <span class="flex gap-1 items-center">
                  <i class="block fa-solid fa-palette text-slate-700 text-lg"></i>
                  <%= glaze.primary_color.titleize %>
                </span>
                <span class="flex gap-1 items-center">
                  <i class="block fa-solid fa-fire text-slate-700 text-lg"></i>
                  <%= glaze.cone_range %>
                </span>
                <span class="flex gap-1 items-center">
                  <i class="block fa-solid fa-utensils text-slate-700 text-lg"></i>
                  <%= glaze.food_safe ? "Yes" : "No" %>
                </span>
              </div>
              <p class="my-3 font-normal text-sm text-slate-700"><%= glaze.description %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <input name="tabs" tabindex="1" type="radio" id="#resources" class="absolute cursor-pointer w-0 opacity-0"/>
  <label for="#resources" class="cursor-pointer inline-flex items-center justify-center gap-2 p-4 font-bold border-b-2 border-transparent rounded-t-lg hover:text-slate-600 hover:border-slate-300 border-blue-600">
    <i class="block fa-solid fa-photo-film text-slate-700 text-xl"></i>
    Resources
  </label>
  <div class="panel my-5">
    <div class="w-full flex flex-col gap-4 md:flex-row justify-between">
      <div class="flex-1">
        <div class="prose">
          <h2>Beginner Throwing Videos:</h2>
          <ol>
            <li><a href="https://www.youtube.com/watch?v=-YCGK33c0xs">How to Center Clay</a></li>
            <li><a href="https://www.youtube.com/watch?v=69dMLpXosSk">How to Cone Clay on the Wheel</a></li>
            <li><a href="https://www.youtube.com/watch?v=HF5IAJ0x2g0">How to Open Up Centered Clay</a></li>
            <li><a href="https://www.youtube.com/watch?v=VM8SJZ4lNRY">How to Pull Up The Walls of a Pot</a></li>
            <li><a href="https://www.youtube.com/watch?v=05CsVxlULo0">How to Lift Pots Off the Wheel</a></li>
          </ol>
          <h2>Intermediate Throwing Videos:</h2>
          <ol>
            <li><a href="https://www.youtube.com/watch?v=6RdfuvSH7UM">How to Center Larger Lumps of Clay</a></li>
            <li><a href="https://www.youtube.com/watch?v=w-k0mkO4qGQ">Discussing Rims &amp; Bottoms</a></li>
            <li><a href="https://www.youtube.com/watch?v=cMWwkrODJRc">5 Tips &amp; Tricks for Centering Clay</a></li>
            <li><a href="https://www.youtube.com/watch?v=Ec9WcarGSTo">5 Tips &amp; Tricks for Throwing</a></li>
            <li><a href="https://www.youtube.com/watch?v=xPgPKRuFia4">How to Throw a Pottery Bowl</a></li>
            <li><a href="https://www.youtube.com/watch?v=nV3a94HlP6g">How to Make Teapots 101</a></li>
            <li><a href="https://www.youtube.com/watch?v=j_rRY_8ObXs">How to make Pouring Vessels</a></li>
            <li><a href="https://www.youtube.com/watch?v=syMSaMygYC4">One Trick to Help Throwing Shallow Bowls</a></li>
          </ol>
        </div>
      </div>
      <div class="flex-1">
        <div class="prose">
          <h2>Beginner Trimming Videos</h2>
          <ol>
            <li><a href="https://www.youtube.com/watch?v=3lBnDWya0r0">The Definitive Tap Centering Tutorial</a></li>
            <li><a href="https://www.youtube.com/watch?v=PiHYWP7UB4w">Trimming Pottery 101</a></li>
            <li><a href="https://www.youtube.com/watch?v=XhlJLVL-Zg8">How to Trim Pots - Tips &amp; Tricks</a></li>
          </ol>
          <h2>Beginner Glazing &amp; Decorating:</h2>
          <ol>
            <li><a href="https://www.youtube.com/watch?v=7oYCoBMVXLU">How to Glaze and Tidy Pots</a></li>
            <li><a href="https://ceramicartsnetwork.org/pottery-making-illustrated/pottery-making-illustrated-article/8-Ways-to-Apply-Glaze">8 Ways to Apply Glaze</a></li>
            <li><a href="https://www.kness.fr/en/underglazes/">A Beginner's Guide to Underglaze</a></li>
            <li><a href="https://www.youtube.com/watch?v=03I49swV6EA">How to Use Wax Resist</a></li>
            <li><a href="https://ceramicartsnetwork.org/daily/article/how-to-set-yourself-up-for-successful-clay-carving">How to Set Yourself Up for Successful Clay Carving</a></li>
            <li><a href="https://www.youtube.com/watch?v=bh8QQ7EqiBE">10 Tips for Carving Pottery</a></li>
          </ol>
          <h2>Miscellaneous</h2>
          <ul>
            <li><a href="https://www.oldforgecreations.co.uk/blog/clay-shrinkage">Clay Shrinkage</a></li>
            <li><a href="https://www.oldforgecreations.co.uk/blog/mug-handles">How To Make Comfortable Mug Handles</a></li>
            <li><a href="https://www.oldforgecreations.co.uk/blog/how-to-stamp-clay">How To Stamp Clay</a></li>
            <li><a href="https://www.oldforgecreations.co.uk/blog/silicosis-what-it-is-and-how-to-avoid-it">Silicosis - What it is and how to avoid it</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  (function () {
      const selectTargetedTab = () => {
          const targetTab = document.querySelector(`input[name="tabs"][id="${window.location.hash}"]`)
          if (targetTab) {
              targetTab.checked = true;
          }
      }

      window.addEventListener("hashchange", selectTargetedTab);

      if (window.location.hash.length <= 1) {
          document.querySelector(`input[name="tabs"][id="#guide"]`).click()
      }

      document.querySelectorAll('input[name="tabs"]').forEach((elem) => {
          elem.addEventListener('click', (event) => {
              history.replaceState({}, '', elem.getAttribute('id'));
              selectTargetedTab();
          })
      });

      selectTargetedTab()
  })();
</script>